name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    env:
        CXXFLAGS: "-O2 -fsanitize=address -Wall -Werror"

    steps:
      - name: 'Clone freedom-devicetree-tools'
        uses: actions/checkout@v2
        with:
          path: freedom-devicetree-tools
          fetch-depth: 1
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build freedom-devicetree-tools container'
        run: |
          docker build -t freedom-devicetree-tools \
            -f freedom-devicetree-tools/docker/Dockerfile \
            freedom-devicetree-tools

      - name: 'Run Clang code style test'
        run: |
          docker run --rm -v $(pwd)/freedom-devicetree-tools:/freedom-devicetree-tools \
            freedom-devicetree-tools ./scripts/check-format

      - name: 'Build and check'
        run: |
          docker run --rm -v $(pwd)/freedom-devicetree-tools:/freedom-devicetree-tools \
            freedom-devicetree-tools \
            sh -c "./configure && make && make install && make check && \
                   cat test-suite.log && make dist && make distcheck"

      - name: 'Build from distribution and check'
        run: |
          docker run --rm -v $(pwd)/freedom-devicetree-tools:/freedom-devicetree-tools \
            freedom-devicetree-tools \
            sh -c "tar -xvzpf freedom-devicetree-tools-*.tar.gz && \
                   cd freedom-devicetree-tools-*/ && ./configure && \
                   make && make install && make check && cat test-suite.log"
